theme: jekyll-theme-minimal
title: eztrackr - ease your job hunt
description: Ease your job hunt by adding your jobs in an organized Trello board
logo: https://i.imgur.com/pGMgpRU.png
show_downloads: false
google_analytics: UA-111263623-1
